### PR TITLE
Update locks

### PR DESCRIPTION
**Pull request by jtpio**
Update the `lab` environment to use the final versions, and remove the `rc` channels.

### CODE REVIEW

**Comment by jtpio** [comment]
Also checking if this might fix #29 with the following link:

https://mybinder.org/v2/gh/jtpio/robotframework-jupyterlibrary/update-final?urlpath=lab/tree/docs/MAGIC.ipynb

**Comment by bollwyvl** [comment]
Thanks so much! Really sorry I haven't gotten back around to this. I see the binder has exploded... not sure why the entropy checking is no good there (it shouldn't need to solve the lock environment in binder).

Aside: I'd really be interested in your feedback on other useful keywords... if they are in the wild, #26 would be great place to put them, otherwise issue-per-keyword-family is rad.

**Comment by bollwyvl** [comment]
In `lock.py`, I bet if you move `from conda.models.match_spec import MatchSpec` inside `expand_specs` it will _work_ (though might need some lint ignore juice)...

**Comment by bollwyvl** [comment]
Gah, maybe this is better: add to `dodo.py`:

```
# at some point, we'll want a scheduled excursion just for locking
if not (P.CI or P.IN_BINDER):

    def task_lock():
```

**Comment by jtpio** [comment]
> Aside: I'd really be interested in your feedback on other useful keywords...

yeah I've been thinking on how we could use this with other clients such as voila and jupyterlab-classic. Sounds like it would make sense to discuss that in https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/issues/26 for sure :+1:

**Comment by bollwyvl** [comment]
> jupyterlab-classic

skipping around between multiple tabs is a pretty serious pain to test, but otherwise should be alright. the ideal would be to reuse as much as possible from lab, and have a very thin set of overlay keywords. If you build a lot of new CSS classes... meh. 

My real goal is to eventually be a bit cleverer, so instead of `Execute JupyterLab Command`, it's just `Execute Command` (and would know to do the right thing, because you had already `Open JupyterLab`ed.

**Comment by bollwyvl** [comment]
`conda` also fails `pip check` because of the `ruamel-yaml` debacle.

**Comment by bollwyvl** [comment]
> voila

sooo.... i haven't been following too closely, but is voila going to support lab3-based federated modules? the use of (or config setup to not need) `unpkg` is untenable for basically all of my use cases...

**Comment by bollwyvl** [comment]
i reckon if you roll back to 0f80c63 (where CI passed) and then cherry-pick 9137a2d (which got binder further) it will be :heavy_check_mark:

**Comment by bollwyvl** [comment]
> Locally I had to fiddle with this extra step to be able to run the lab task

Yeah... it's a bit of an odd beast, and not entirely to my liking... but since we're testing a test environment... normally, i don't install `geckodriver` and `firefox` in the same env as my system-under-test.

**Comment by jtpio** [comment]
> is voila going to support lab3-based federated modules?

Yes, we are planning to make the Voila frontend a lab-based frontend using 3.0 packages, so existing mime renderers and widgets should work out of the box. There are a couple of smaller steps before this (for example moving to TS), but in any case improving on the end-to-end testing should help catch potential issues when making such changes.

**Comment by jtpio** [comment]
> i reckon if you roll back to [0f80c63](https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/commit/0f80c63a1704a23aeaf5d9befac23c1fedcbe13f) (where CI passed) and then cherry-pick [9137a2d](https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/commit/9137a2d53df8f2ebdddf248fb4103a3ed1e116a6) (which got binder further) it will be heavy_check_mark

sure, will do :+1:

**Comment by jtpio** [comment]
Looks like the Binder is starting now. Thanks!

image

**Comment by bollwyvl** [comment]
Sorry, I was getting some weird stale state in my browser, and thought some jobs were failing... opened it in another browser, and saw that it was all :heavy_check_mark: ! Going to take a quick spin around the binder, and very likely merge soon thereafter. Thanks again!

**Pull request merged**
