### PR TITLE
ci: allow ci workflow to be manually triggered

### PR DESCRIPTION
**Pull request by consideRatio**
This PR enables the CI workflow to run manually by the click of a button (by repo maintainers).

## Example of the button from another repo

image

### CODE REVIEW

**Comment by bollwyvl** [comment]
Sure, thanks... but it won't help debug #65, as the lab 3 excursion currently [pinned rather hard](https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/blob/master/.github/locks/test/linux-64/py3.10/lab3/conda.lock) against an older version of jupyter_server, and takes a bit of doing to add another factor to the matrix.

**Comment by consideRatio** [comment]
@bollwyvl ah yes I realized that recently in #65 =/

**Comment by consideRatio** [comment]
> the lab 3 excursion currently [pinned rather hard](https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/blob/master/.github/locks/test/linux-64/py3.10/lab3/conda.lock) against an older version of jupyter_server, and takes a bit of doing to add another factor to the matrix.

If you keep testing against py37 you could get the jupyter_server 1 automatically retained, while tests in py3.10/3.11 would provide jupyter_server 2 with jupyterlab 3.5+. That way, you would have tests with jupyter_server 1 and 2 without duplicating the amounts of tests or manually handling where and when jupyter_server 2 should be adopted as that would be decided by version compatebility in requested dependencies.

**Comment by consideRatio** [comment]
I guess the crux here is that the lab3 spec includes retrolab, which pins jupyter server 1 still. See https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/blob/master/.github/env_specs/lab3.yml#L13

**Pull request merged**
