### PR TITLE
Add conda forge installation instruction

### PR DESCRIPTION
**Pull request by martinRenou**
`robotframework-jupyterlibrary` is on conda-forge!

I am actually looking forward to using this library for doing more UI tests in Jupyter. I am hoping to use it in some Jupyter widgets libraries.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Smashing! Will review when next at keyboard but will very likely merge, and
get RTD working again.

Beyond that, a new release of this is certainly in order: I'm pretty sure
it only speaks lab 1 (or early lab 2) CSS selectors. Also we've done a lot
of heavy copy/paste customization on jupyterlab-lsp and other projects that
would be good to codify here.

Beyond that release (or as a rapid prerelease), Lab 3 is going to be a
bruiser to support well, but will be super fun: of particular interest will
be supporting the ability to start lab with different extension,
localization, and accessibility options. @datakurre had some accessibility
tools we might be able to make work with modern Firefox.

Please let us know if you'd be interested in joining the org/team, if you
have any interest in seeing some of these things land at an accelerated
pace!

**Comment by bollwyvl** [comment]
Going to merge as-is, will deal with the fall-out on a subsequent PR.

**Comment by datakurre** [comment]
I was mentioned about accessibility tools... yes, I did automate a few Firefox extensions years ago. 

By chance, I was able to return to that lately. I've been very recently automating WebAIM Wave and SiteImprove extensions on Chrome with Selenium and OpenCV + PyAutoGUI. Obviously, automating against their web service is forbidden, but hey both claim that their extensions run completely offline, so automating those should be okay. PyAutoGUI is required, because due to web extension sandboxing, those extensions can only be interacted with desktop automation tools. I believe, I could publish details on automating WebAIM Wave. SiteImprove requires monkeypatching the extension during webdriver initialization for machine readable results, which is more on the gray area...

**Comment by martinRenou** [comment]
> I'm pretty sure it only speaks lab 1 (or early lab 2) CSS selectors

I have to say that I saw some tests running and passing using robotframework-jupyterlibrary with JupyterLab 3.

> Please let us know if you'd be interested in joining the org/team, if you have any interest in seeing some of these things land at an accelerated pace!

Well for now I am at the "This looks super cool and handy" stage with robotframework, I have to admit I did not try playing with it yet but I am looking forward to it! I can add you both as a conda package maintainer if you want. I'd be happy to join the org if you think that makes sense!

**Comment by bollwyvl** [comment]
> I have to say that I saw some tests running and passing using robotframework-jupyterlibrary with JupyterLab 3.

Yeah, the core server stuff that handles "start an isolated" isn't concerned by which client is running at all, as long as its supports the core CLI config switches.

I still need to test on lab 1 and 2 for some projects. So: my intent is to have some optional keywords, and some client detection (perhaps by listing serverextension versions) that can load the correct version of at least CSS selectors. On Lab 2, anything related to icons, that are out of date, so some of the keywords don't work. And I've barely looked into it, but the Lab 3 DOM changed substantially around the command palette, so that will require some special handling.

As mentioned, on some of the other projects, we overload a lot more switches for more robust tests. For example, on Lab 2.2+, it's possible to disable all of the node build checks, which avoids ever seeing the horrible "hey do you want to rebuild" dialogs which show up... whenever node/npm finishes doing its stuff. Won't need these on 3, but the config will be a little more interesting, as we could start a server with a reduced set of extensions.

> happy to join the org if you think that makes sense

Just if there's burning stuff keeping your tests from working well on whatever you need!

**Pull request merged**
